### ISSUE TITLE
Add wiki page on how to submit new data and what data are acceptable

### ISSUE THREAD

**Issue by bryanwweber** [pr-omethe-us/ChemKED-database#4]
Following the discussion in pr-omethe-us/PyKED#55, I propose that we add a wiki page to this repository with instructions for how to generate ChemKED files and submit them to the database. In addition, we should include criteria for data to be included.

**Comment by bryanwweber** [comment]
As I said in pr-omethe-us/PyKED#55, in my opinion, the criteria for inclusion should be that the data have a permanent identifier. This could include

* arXiv
* figshare (DOI)
* zenodo (DOI)
* DOI
* others?

Perhaps we can also use this issue to draft text for the wiki page?

**Comment by kyleniemeyer** [comment]
Yes, I agree. Pretty much all services like this give you a DOI now, with the notable exception of arXiv (which has it's own permanent identifier), so it doesn't seem unreasonable to require this. The main challenge is getting our community to catch up to these advances :)

One other challenge will be validating the non-CrossRef DOIs. I believe most others are DataCite, which inevitably has an API, and hopefully a Python tool for interacting with it...

**Comment by mefuller** [comment]
I made a draft wiki page based on what I know, but I see know way to open a PR: 
https://github.com/mefuller/ChemKED-database/wiki

**Comment by bryanwweber** [comment]
I don't think you can open PRs for Wiki pages, but it looks like you can just create the page here! That text looks good.

**Comment by mefuller** [comment]
It doesn't appear that I have permission to do so - I'm not in the pr.omethe.us group and I'm only a maintainer on PyKED, I believe

**Comment by bryanwweber** [comment]
OK, I'm not an admin of this repo, so we have to ping @kyleniemeyer to open up access.

**Comment by kyleniemeyer** [comment]
Sure - do I need to give @mefuller write access?

**Comment by kyleniemeyer** [comment]
(@bryanwweber I did just make you an admin as well)

**Comment by kyleniemeyer** [comment]
@mefuller I have given you write access to this repo

**Comment by mefuller** [comment]
Something still isn't working right as clicking on "wiki" just loops me back around to the main page
I also have no access to the repo settings - is the wiki disabled there by chance?

**Comment by kyleniemeyer** [comment]
@mefuller hmm. I just created the first wiki page, so it seems enabled, and also elevated your access role to "maintain". See if that fixes it?

**Comment by mefuller** [comment]
@kyleniemeyer well, I can see it now and I have option to clone it, but no option to edit

EDIT: you've probably seen it, but this is all I can find about the issue: https://docs.github.com/en/github/building-a-strong-community/changing-access-permissions-for-wikis

**Comment by rwest** [comment]
I'm sure we could get to the bottom of the wiki thing, but how about we just have a long readme file instead? It's there right on the landing page, and everybody can open pull requests without any admin faffing around￼
